# Generated by Django 4.1.7 on 2023-03-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('added_date', models.DateTimeField(verbose_name='added date')),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200)),
                ('device_displayed_name', models.CharField(blank=True, max_length=200, null=True)),
                ('device_description', models.CharField(blank=True, max_length=400, null=True)),
                ('device_serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('device_add_date', models.DateTimeField(verbose_name='Added')),
                ('device_bought_date', models.DateTimeField(verbose_name='Bought')),
                ('device_warranty', models.CharField(choices=[('Active', 'Warranty still active'), ('Inactive', 'Warranty not activated'), ('Finished', 'Warranty finished')], max_length=10)),
                ('device_db_index', models.IntegerField(unique=True)),
                ('user_connected', models.CharField(max_length=200)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevOrg.devicetypes')),
            ],
        ),
    ]
